#!/bin/sh

proxy_addr=${PROXY_ADDR:-files.m.daocloud.io}

for app in $@; do
	url=$(brew info --json=v2 ${app} | jq -r 'if (.formulae | length) > 0 then .formulae[0].bottle.stable.files.arm64_sequoia.url elif (.casks | length) > 0 then .casks[0].url end')
	if [ -z "${url}" ]; then
		printf "parse %s's download url\n" ${app}
		continue
	fi
	proxy_url=${url/:\/\//://${proxy_addr}/}
	curl -SL -# "${proxy_url}" -o $(brew --cache)/downloads/$(sha256 -s ${url})--$(basename ${url})
done
