name: Bump formula on upstream release

on:
  schedule:
    - cron: '0 0 1,11,21 * *'
  workflow_dispatch:   # 允许手动触发

jobs:
  bump:
    runs-on: macos-latest   # 或 ubuntu-latest，但 macOS 有 Homebrew 预装
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew tap
        run: brew tap morii0v0/homebrew-core

      - name: Bump formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          BREW_TAP_NAME: ${{ vars.BREW_TAP_NAME }}
        run: |
          brew bump-formula-pr \
            --message="Update formula to latest version" \
            --no-browse \
            ${BREW_TAP_NAME}/openvpn3
